Several enhancements
Haarolean/gnutard-bot pull request #3
Opened 2024-04-07 20:47 UTC by divide-by-null

2024-04-13 18:00 UTC, Haarolean requested changes

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/UnpinDiscussionAbility.kt
> +        if(message == null) return false
`message == null` -> `!ctx.update().hasMessage()`

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/BanAbility.kt
> +        if(reply == null) return
Please run the formatter here

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/TrollingAbility.kt
> +        return message.text.contains("windows".toRegex(RegexOption.IGNORE_CASE))
let's extract this as a class field. Something like:
`private final Pattern WINDOWS_PATTERN = Pattern.compile(".*windows.*")`
and
`WINDOWS_PATTERN.matcher(message.text).matches()`

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/TrollingAbility.kt
> +        val senderTag = '@' + message.from.userName
username might be missing as it's possible to not have one on telegram

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/TrollingAbility.kt
> +        val senderTag = '@' + message.from.userName
and there's no point in tagging if we're replying to a message tbh

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/TrollingAbility.kt
> +}
please add an empty line in each file, this is a best practice to prevent unnecessary merge conflicts in git

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/TrollingAbility.kt
> +    private val replyMessages = arrayOf(
this could be moved outside of class declaration as this *in kotlin* will be initialized every time a class instance is created

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/CheckLinksAbility.kt
> -        // https://github.com/rubenlagus/TelegramBots/issues/1296
is this not applicable here anymore? Please elaborate

2024-04-13 18:00 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/CheckLinksAbility.kt
> +        if (Flag.MESSAGE.test(update) || Flag.EDITED_MESSAGE.test(update)) return false
this looks incorrect, as here we care only about text messages, so it's either Flag.MESSAGE or Flag.EDITED_MESSAGE.

2024-04-14 14:20 UTC, divide-by-null commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/CheckLinksAbility.kt
> -        // https://github.com/rubenlagus/TelegramBots/issues/1296
This method was refactored to `isApplicable` method which you commented below

2024-04-21 04:06 UTC, Haarolean requested changes

2024-04-21 04:06 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/TrollingAbility.kt
> +        if(update.message.isUserMessage) return false
please apply formatting to all the classes

2024-04-21 04:06 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/TrollingAbility.kt
> +        val messageText = replyMessages[Random.nextInt(replyMessages.size - 1)]
`replyMessages.random()`

2024-04-21 04:06 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/NukeAbility.kt
> +            .locality(Locality.ALL)
what's the reason behind changing the `Locality`?

2024-04-21 04:06 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/DefaultAbility.kt
> +            .locality(Locality.ALL)
since we're using `Locality.ALL` for all the abilities here now, there's a check in `UnpinDiscussionAbility` missing to check if it's a group message rather than a user's.

2024-04-21 04:06 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/DefaultAbility.kt
> +            .findFirst()
findFirst -> forEach, as I believe we could have multiple abilities triggered for the same event in the future

2024-04-21 04:06 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/CheckLinksAbility.kt
> -@Scope(BeanDefinition.SCOPE_PROTOTYPE)
different abilities now have a different set of annotations or none at all. Let's make them identical, please

2024-04-22 16:17 UTC, Haarolean approved these changes
Thanks for your first contribution to gnutard bot!

2024-04-22 16:19 UTC, merged

2024-04-22 16:39 UTC, divide-by-null commented
> Thanks for your first contribution to gnutard bot!

I saw it it my dream