Feature: ban channel messages
Haarolean/gnutard-bot pull request #8
Opened 2024-04-20 09:12 UTC by divide-by-null

2024-04-22 16:19 UTC, Haarolean commented
@divide-by-null could you rebase please?

2024-04-22 17:49 UTC, divide-by-null commented
> @divide-by-null could you rebase please?

Done!

2024-05-03 22:10 UTC, Haarolean requested changes

2024-05-03 22:10 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/app/props/BotProperties.kt
> +     val allowedSenderChatsUsernames: Set<String>
this should be rather ids than usernames

2024-05-03 22:10 UTC, Haarolean commented on src/main/kotlin/dev/haarolean/gnutardbot/abilities/BanSenderChatMessagesAbility.kt
> +        val banSenderChatRequest = BanChatSenderChat
does this actually work for the channels? what happens if we try to select a channel as a sender which was previously banned?

2025-01-09 16:34 UTC, closed without merging